/*
 * Copyright (C) 2016 ntko
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package automateyourjob;

import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ntko
 */
public class AutomateYourJobUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AutomateYourJobUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    // Lists the employment.template in an ArrayList
    static ArrayList<String> employmentRead() {
        ArrayList<String> fileRead = null;
        try {
            ReadTemplate r = new ReadTemplate();
            String fileName = "employment.template";

            fileRead = r.ReadTemplate(fileName);
        }catch (IOException ex) {
            Logger.getLogger(AutomateYourJob.class.getName()).log(Level.SEVERE, null, ex);
        }
        return fileRead;
    }
    // Lists the education.template in an ArrayList
    static ArrayList<String> educationRead() {
        ArrayList<String> fileRead = null;
        try {
            ReadTemplate r = new ReadTemplate();
            String fileName = "education.template";

            fileRead = r.ReadTemplate(fileName);
        }catch (IOException ex) {
            Logger.getLogger(AutomateYourJob.class.getName()).log(Level.SEVERE, null, ex);
        }
        return fileRead;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        employmentEdit = new javax.swing.JPanel();
        jEmploymentLabel1 = new javax.swing.JLabel();
        jEmploymentLabel2 = new javax.swing.JLabel();
        jEmploymentReferee = new javax.swing.JTextField();
        jEmploymentTitle = new javax.swing.JTextField();
        jEmploymentMainText = new javax.swing.JTextField();
        jEmploymentDate1 = new javax.swing.JTextField();
        jEmploymentTo = new javax.swing.JTextField();
        jEmploymentDate2 = new javax.swing.JTextField();
        jEmploymentPositionText = new javax.swing.JTextField();
        jEmploymentPosition = new javax.swing.JTextField();
        jEmploymentSalaryText = new javax.swing.JTextField();
        jEmploymentSalary = new javax.swing.JTextField();
        jEmploymentSaveButton = new javax.swing.JButton();
        jEmploymentDefaultButton = new javax.swing.JButton();
        jEmploymentLoadButton = new javax.swing.JButton();
        jEmploymentScrollPane = new javax.swing.JScrollPane();
        jEmploymentInfoText = new javax.swing.JTextArea();
        educationEdit = new javax.swing.JPanel();
        jEducationReferee = new javax.swing.JTextField();
        jEducationTitle = new javax.swing.JTextField();
        jEducationDate1 = new javax.swing.JTextField();
        jEducationDate2 = new javax.swing.JTextField();
        jEducationLabel1 = new javax.swing.JLabel();
        jEducationMainText = new javax.swing.JTextField();
        jEducationTo = new javax.swing.JTextField();
        jEducationAwarded = new javax.swing.JTextField();
        jEducationSaveButton = new javax.swing.JButton();
        jEducationLoadButton = new javax.swing.JButton();
        jEducationDefaultButton = new javax.swing.JButton();
        awaitingPublishing = new javax.swing.JPanel();
        jEducationPublish = new javax.swing.JButton();
        jEmploymentPublish = new javax.swing.JButton();
        jProfQualPublish = new javax.swing.JButton();
        jMembership = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jEmploymentShort = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jMenuHome = new javax.swing.JMenuItem();
        jAwaitingPublishing = new javax.swing.JMenuItem();
        jCandidateComms = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jEditTemplate = new javax.swing.JMenu();
        jMenuEmploymentEdit = new javax.swing.JMenuItem();
        jMenuEducationEdit = new javax.swing.JMenuItem();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        mainPanel.setPreferredSize(new java.awt.Dimension(770, 259));
        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        mainPanel.add(homePanel, "homePanel");

        employmentEdit.setInheritsPopupMenu(true);
        employmentEdit.setPreferredSize(new java.awt.Dimension(770, 259));

        jEmploymentLabel1.setText("Separate parts are modifiable");

        jEmploymentLabel2.setText("These fields will not appear if the data hasn't been entered");

        jEmploymentReferee.setEditable(false);
        jEmploymentReferee.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentReferee.setText("<Referee>");

        jEmploymentTitle.setEditable(false);
        jEmploymentTitle.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentTitle.setText("(<Title>)");

        jEmploymentMainText.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentMainText.setText(employmentRead().get(0));

        jEmploymentDate1.setEditable(false);
        jEmploymentDate1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentDate1.setText("<Date 1>");

        jEmploymentTo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentTo.setText(employmentRead().get(1));

        jEmploymentDate2.setEditable(false);
        jEmploymentDate2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentDate2.setText("<Date 2>");

        jEmploymentPositionText.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentPositionText.setText(employmentRead().get(2));

        jEmploymentPosition.setEditable(false);
        jEmploymentPosition.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentPosition.setText("<Position>");

        jEmploymentSalaryText.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentSalaryText.setText(employmentRead().get(3));

        jEmploymentSalary.setEditable(false);
        jEmploymentSalary.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEmploymentSalary.setText("<salary>");

        jEmploymentSaveButton.setText("Save");
        jEmploymentSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmploymentSaveButtonActionPerformed(evt);
            }
        });

        jEmploymentDefaultButton.setText("Default");
        jEmploymentDefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmploymentDefaultButtonActionPerformed(evt);
            }
        });

        jEmploymentLoadButton.setText("Load");
        jEmploymentLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmploymentLoadButtonActionPerformed(evt);
            }
        });

        jEmploymentInfoText.setColumns(20);
        jEmploymentInfoText.setRows(5);
        jEmploymentInfoText.setText(employmentRead().get(4));
        jEmploymentScrollPane.setViewportView(jEmploymentInfoText);

        javax.swing.GroupLayout employmentEditLayout = new javax.swing.GroupLayout(employmentEdit);
        employmentEdit.setLayout(employmentEditLayout);
        employmentEditLayout.setHorizontalGroup(
            employmentEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employmentEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employmentEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEmploymentScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentEditLayout.createSequentialGroup()
                        .addComponent(jEmploymentLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEmploymentLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentEditLayout.createSequentialGroup()
                        .addComponent(jEmploymentReferee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jEmploymentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmploymentMainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmploymentDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmploymentTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmploymentDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmploymentPositionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmploymentPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmploymentSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEmploymentSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employmentEditLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jEmploymentSaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEmploymentLoadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEmploymentDefaultButton)))
                .addContainerGap())
        );
        employmentEditLayout.setVerticalGroup(
            employmentEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employmentEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(employmentEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmploymentLabel2)
                    .addComponent(jEmploymentLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employmentEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmploymentReferee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmploymentTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmploymentMainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmploymentDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmploymentTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmploymentDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmploymentPositionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmploymentPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmploymentSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmploymentSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEmploymentScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(employmentEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmploymentDefaultButton)
                    .addComponent(jEmploymentLoadButton)
                    .addComponent(jEmploymentSaveButton))
                .addContainerGap())
        );

        mainPanel.add(employmentEdit, "employmentEdit");

        jEducationReferee.setEditable(false);
        jEducationReferee.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEducationReferee.setText("<Referee>");

        jEducationTitle.setEditable(false);
        jEducationTitle.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEducationTitle.setText("(<Title>)");

        jEducationDate1.setEditable(false);
        jEducationDate1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEducationDate1.setText("<Date 1>");

        jEducationDate2.setEditable(false);
        jEducationDate2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jEducationDate2.setText("<Date 2>");

        jEducationLabel1.setText("Separate parts are modifiable");

        jEducationMainText.setText(educationRead().get(0));

        jEducationTo.setText(educationRead().get(1));

        jEducationAwarded.setText(educationRead().get(2));

        jEducationSaveButton.setText("Save");
        jEducationSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEducationSaveButtonActionPerformed(evt);
            }
        });

        jEducationLoadButton.setText("Load");
        jEducationLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEducationLoadButtonActionPerformed(evt);
            }
        });

        jEducationDefaultButton.setText("Default");
        jEducationDefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEducationDefaultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout educationEditLayout = new javax.swing.GroupLayout(educationEdit);
        educationEdit.setLayout(educationEditLayout);
        educationEditLayout.setHorizontalGroup(
            educationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(educationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(educationEditLayout.createSequentialGroup()
                        .addComponent(jEducationReferee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEducationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEducationMainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEducationDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEducationTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEducationDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEducationAwarded, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                    .addGroup(educationEditLayout.createSequentialGroup()
                        .addComponent(jEducationLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, educationEditLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jEducationSaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEducationLoadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEducationDefaultButton)))
                .addContainerGap())
        );
        educationEditLayout.setVerticalGroup(
            educationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jEducationLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(educationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEducationReferee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEducationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEducationMainText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEducationDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEducationDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEducationTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEducationAwarded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addGroup(educationEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEducationDefaultButton)
                    .addComponent(jEducationLoadButton)
                    .addComponent(jEducationSaveButton))
                .addContainerGap())
        );

        mainPanel.add(educationEdit, "educationEdit");

        jEducationPublish.setText("Education");

        jEmploymentPublish.setText("Employment");
        jEmploymentPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmploymentPublishActionPerformed(evt);
            }
        });

        jProfQualPublish.setText("Prof Qual");

        jMembership.setText("Membership");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Reference OK:");

        jEmploymentShort.setText("Employment");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Short Reference:");

        javax.swing.GroupLayout awaitingPublishingLayout = new javax.swing.GroupLayout(awaitingPublishing);
        awaitingPublishing.setLayout(awaitingPublishingLayout);
        awaitingPublishingLayout.setHorizontalGroup(
            awaitingPublishingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(awaitingPublishingLayout.createSequentialGroup()
                .addGroup(awaitingPublishingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(awaitingPublishingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jEducationPublish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jMembership, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProfQualPublish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jEmploymentPublish)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(awaitingPublishingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEmploymentShort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        awaitingPublishingLayout.setVerticalGroup(
            awaitingPublishingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, awaitingPublishingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(awaitingPublishingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(awaitingPublishingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmploymentShort)
                    .addComponent(jEmploymentPublish))
                .addGap(5, 5, 5)
                .addComponent(jEducationPublish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProfQualPublish)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMembership)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(awaitingPublishing, "awaitingPublishing");

        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseReleased(evt);
            }
        });

        jFile.setText("File");

        jMenuHome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuHome.setText("Home");
        jMenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHomeActionPerformed(evt);
            }
        });
        jFile.add(jMenuHome);

        jAwaitingPublishing.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jAwaitingPublishing.setText("Awaiting Publishing");
        jAwaitingPublishing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAwaitingPublishingActionPerformed(evt);
            }
        });
        jFile.add(jAwaitingPublishing);

        jCandidateComms.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jCandidateComms.setText("Candidate Comms");
        jFile.add(jCandidateComms);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("Other");
        jFile.add(jMenuItem5);

        jMenuBar1.add(jFile);

        jEditTemplate.setText("Edit Template");

        jMenuEmploymentEdit.setText("Employment");
        jMenuEmploymentEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmploymentEditActionPerformed(evt);
            }
        });
        jEditTemplate.add(jMenuEmploymentEdit);

        jMenuEducationEdit.setText("Education");
        jMenuEducationEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEducationEditActionPerformed(evt);
            }
        });
        jEditTemplate.add(jMenuEducationEdit);

        jMenuBar1.add(jEditTemplate);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void jMenuEmploymentEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmploymentEditActionPerformed
    CardLayout card = (CardLayout)mainPanel.getLayout();
    card.show(mainPanel, "employmentEdit");
    }//GEN-LAST:event_jMenuEmploymentEditActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void jMenuBar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1MouseReleased

    private void jEmploymentSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmploymentSaveButtonActionPerformed
        try {
            String employmentURL = "employment.template";
            
            WriteTemplate writer = new WriteTemplate(employmentURL, 
                    jEmploymentMainText, jEmploymentTo, jEmploymentPositionText,
                    jEmploymentSalaryText, jEmploymentInfoText);
        } catch (IOException ex) {
            Logger.getLogger(AutomateYourJob.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jEmploymentSaveButtonActionPerformed

    private void jMenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHomeActionPerformed
    CardLayout card = (CardLayout)mainPanel.getLayout();
    card.show(mainPanel, "homePanel");
    }//GEN-LAST:event_jMenuHomeActionPerformed

    private void jEmploymentDefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmploymentDefaultButtonActionPerformed
            jEmploymentMainText.setText("advised that the Candidate was employed from");
            jEmploymentTo.setText("to");
            jEmploymentPositionText.setText("in the position of");
            jEmploymentSalaryText.setText("with a salary of");
            jEmploymentInfoText.setText("The Referee described the Candidate as \n"
                    + "\n" + "They further advised that the Candidate was "
                    + "honest and showed integrity, and the Candidate's health "
                    + "and disciplinary record were clean.\n" + "\n" + "The "
                    + "reason for leaving stated was XXX and the Company would "
                    + "re-employ the Candidate.");
    }//GEN-LAST:event_jEmploymentDefaultButtonActionPerformed

    private void jEmploymentLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmploymentLoadButtonActionPerformed
        
            // employmentRead() defined on 46. returns array of the read template.
            String main = employmentRead().get(0);
            String to = employmentRead().get(1);
            String position = employmentRead().get(2);
            String salary = employmentRead().get(3);
            String info = employmentRead().get(4);
            jEmploymentMainText.setText(main);
            jEmploymentTo.setText(to);
            jEmploymentPositionText.setText(position);
            jEmploymentSalaryText.setText(salary);
            jEmploymentInfoText.setText(info);

    }//GEN-LAST:event_jEmploymentLoadButtonActionPerformed

    private void jMenuEducationEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEducationEditActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "educationEdit");
    }//GEN-LAST:event_jMenuEducationEditActionPerformed

    private void jEducationSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEducationSaveButtonActionPerformed
        try {
        String educationURL = "education.template";
            WriteTemplate writer = new WriteTemplate(educationURL, jEducationMainText,
                    jEducationTo, jEducationAwarded);
        } catch (IOException ex) {
            Logger.getLogger(AutomateYourJob.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jEducationSaveButtonActionPerformed

    private void jEducationLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEducationLoadButtonActionPerformed
        // educationRead() defined on 59. returns array of the read template.
            String main = educationRead().get(0);
            String to = educationRead().get(1);
            String awarded = educationRead().get(2);
            jEducationMainText.setText(main);
            jEducationTo.setText(to);
            jEducationAwarded.setText(awarded);
    }//GEN-LAST:event_jEducationLoadButtonActionPerformed

    private void jEducationDefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEducationDefaultButtonActionPerformed
            jEducationMainText.setText("advised that the Candidate studied from");
            jEducationTo.setText("to");
            jEducationAwarded.setText("and was awarded:" + "\n" + "\n");
    }//GEN-LAST:event_jEducationDefaultButtonActionPerformed

    private void jAwaitingPublishingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAwaitingPublishingActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "awaitingPublishing");
    }//GEN-LAST:event_jAwaitingPublishingActionPerformed

    private void jEmploymentPublishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmploymentPublishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmploymentPublishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutomateYourJob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel awaitingPublishing;
    private javax.swing.JPanel educationEdit;
    private javax.swing.JPanel employmentEdit;
    private javax.swing.JPanel homePanel;
    private javax.swing.JMenuItem jAwaitingPublishing;
    private javax.swing.JMenuItem jCandidateComms;
    private javax.swing.JMenu jEditTemplate;
    private javax.swing.JTextField jEducationAwarded;
    private javax.swing.JTextField jEducationDate1;
    private javax.swing.JTextField jEducationDate2;
    private javax.swing.JButton jEducationDefaultButton;
    private javax.swing.JLabel jEducationLabel1;
    private javax.swing.JButton jEducationLoadButton;
    private javax.swing.JTextField jEducationMainText;
    private javax.swing.JButton jEducationPublish;
    private javax.swing.JTextField jEducationReferee;
    private javax.swing.JButton jEducationSaveButton;
    private javax.swing.JTextField jEducationTitle;
    private javax.swing.JTextField jEducationTo;
    private javax.swing.JTextField jEmploymentDate1;
    private javax.swing.JTextField jEmploymentDate2;
    private javax.swing.JButton jEmploymentDefaultButton;
    private javax.swing.JTextArea jEmploymentInfoText;
    private javax.swing.JLabel jEmploymentLabel1;
    private javax.swing.JLabel jEmploymentLabel2;
    private javax.swing.JButton jEmploymentLoadButton;
    private javax.swing.JTextField jEmploymentMainText;
    private javax.swing.JTextField jEmploymentPosition;
    private javax.swing.JTextField jEmploymentPositionText;
    private javax.swing.JButton jEmploymentPublish;
    private javax.swing.JTextField jEmploymentReferee;
    private javax.swing.JTextField jEmploymentSalary;
    private javax.swing.JTextField jEmploymentSalaryText;
    private javax.swing.JButton jEmploymentSaveButton;
    private javax.swing.JScrollPane jEmploymentScrollPane;
    private javax.swing.JButton jEmploymentShort;
    private javax.swing.JTextField jEmploymentTitle;
    private javax.swing.JTextField jEmploymentTo;
    private javax.swing.JMenu jFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jMembership;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEducationEdit;
    private javax.swing.JMenuItem jMenuEmploymentEdit;
    private javax.swing.JMenuItem jMenuHome;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JButton jProfQualPublish;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
